version: 1.3
workflows:
 - name: CalculateStudentGPA
   subclass: WDL
   primaryDescriptorPath: /calculate_average_gpa.wdl
 - name: CalculateClassGPA
   subclass: WDL
   primaryDescriptorPath: /calculate_class_average.wdl
